apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: euv7wdre5-nodejs 
  janus-idp.io/tekton: euv7wdre5-nodejs
  backstage.io/kubernetes-id: euv7wdre5-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: euv7wdre5-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml